[project]
name = "coord-convert-gui"
version = "1.0.0"
description = "Coordinate Converter GUI"
requires-python = ">=3.13"
dependencies = [
    "PySide6>=6.8.0",
    "pyproj>=3.7.0",
    "PyGeodesy>=22.6.0",
    "pandas>=2.0.0",
    "openpyxl>=3.1.5",
]

[project.scripts]
coord-convert = "main:main"

[dependency-groups]
dev = []
